---
- name: "Send machine group monitor"
  copy:
    src: "cluster_util-condor-split.sh"
    dest: "/usr/bin/monitor-condor-utilisation-split"
    owner: root
    group: root
    mode: 0755

- name: Allow telegraf to run monitor-condor-utilisation-split
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: EOF
    line: 'telegraf ALL=(ALL) NOPASSWD: /usr/bin/monitor-condor-utilisation-split'
    validate: 'visudo -cf %s'

- name: "Send condor cluster utilisation monitor"
  copy:
    src: "cluster_util-condor.sh"
    dest: "/usr/bin/monitor-condor-utilisation"
    owner: root
    group: root
    mode: 0755

- name: Allow telegraf to run monitor-condor-utilisation
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: EOF
    line: 'telegraf ALL=(ALL) NOPASSWD: /usr/bin/monitor-condor-utilisation'
    validate: 'visudo -cf %s'

- name: "Send condor queue monitor"
  copy:
    src: "cluster_queue-condor.sh"
    dest: "/usr/bin/monitor-condor-queue"
    owner: root
    group: root
    mode: 0755

- name: Allow telegraf to run monitor-condor-queue
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: EOF
    line: 'telegraf ALL=(ALL) NOPASSWD: /usr/bin/monitor-condor-queue'
    validate: 'visudo -cf %s'
